<?php
/**
 * DatabaseChange
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FWGCentralAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Central FWG API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FWGCentralAPI\Model;

use \ArrayAccess;
use \FWGCentralAPI\ObjectSerializer;

/**
 * DatabaseChange Class Doc Comment
 *
 * @category Class
 * @package  FWGCentralAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DatabaseChange implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DatabaseChange';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'f_k_heat_device' => 'int',
        'heat_device' => '\FWGCentralAPI\Model\HeatDevice',
        'f_k_old_region' => 'int',
        'old_region' => '\FWGCentralAPI\Model\Region',
        'f_k_new_region' => 'int',
        'new_region' => '\FWGCentralAPI\Model\Region',
        'old_database_name' => 'string',
        'new_database_name' => 'string',
        'migration_start' => '\DateTime',
        'migration_end' => '\DateTime',
        'rows_affected' => 'int',
        'id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'f_k_heat_device' => 'int32',
        'heat_device' => null,
        'f_k_old_region' => 'int32',
        'old_region' => null,
        'f_k_new_region' => 'int32',
        'new_region' => null,
        'old_database_name' => null,
        'new_database_name' => null,
        'migration_start' => 'date-time',
        'migration_end' => 'date-time',
        'rows_affected' => 'int32',
        'id' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'f_k_heat_device' => false,
        'heat_device' => false,
        'f_k_old_region' => false,
        'old_region' => false,
        'f_k_new_region' => false,
        'new_region' => false,
        'old_database_name' => true,
        'new_database_name' => true,
        'migration_start' => false,
        'migration_end' => true,
        'rows_affected' => true,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'f_k_heat_device' => 'fK_HeatDevice',
        'heat_device' => 'heatDevice',
        'f_k_old_region' => 'fK_OldRegion',
        'old_region' => 'oldRegion',
        'f_k_new_region' => 'fK_NewRegion',
        'new_region' => 'newRegion',
        'old_database_name' => 'oldDatabaseName',
        'new_database_name' => 'newDatabaseName',
        'migration_start' => 'migrationStart',
        'migration_end' => 'migrationEnd',
        'rows_affected' => 'rowsAffected',
        'id' => 'id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'f_k_heat_device' => 'setFKHeatDevice',
        'heat_device' => 'setHeatDevice',
        'f_k_old_region' => 'setFKOldRegion',
        'old_region' => 'setOldRegion',
        'f_k_new_region' => 'setFKNewRegion',
        'new_region' => 'setNewRegion',
        'old_database_name' => 'setOldDatabaseName',
        'new_database_name' => 'setNewDatabaseName',
        'migration_start' => 'setMigrationStart',
        'migration_end' => 'setMigrationEnd',
        'rows_affected' => 'setRowsAffected',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'f_k_heat_device' => 'getFKHeatDevice',
        'heat_device' => 'getHeatDevice',
        'f_k_old_region' => 'getFKOldRegion',
        'old_region' => 'getOldRegion',
        'f_k_new_region' => 'getFKNewRegion',
        'new_region' => 'getNewRegion',
        'old_database_name' => 'getOldDatabaseName',
        'new_database_name' => 'getNewDatabaseName',
        'migration_start' => 'getMigrationStart',
        'migration_end' => 'getMigrationEnd',
        'rows_affected' => 'getRowsAffected',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('f_k_heat_device', $data ?? [], null);
        $this->setIfExists('heat_device', $data ?? [], null);
        $this->setIfExists('f_k_old_region', $data ?? [], null);
        $this->setIfExists('old_region', $data ?? [], null);
        $this->setIfExists('f_k_new_region', $data ?? [], null);
        $this->setIfExists('new_region', $data ?? [], null);
        $this->setIfExists('old_database_name', $data ?? [], null);
        $this->setIfExists('new_database_name', $data ?? [], null);
        $this->setIfExists('migration_start', $data ?? [], null);
        $this->setIfExists('migration_end', $data ?? [], null);
        $this->setIfExists('rows_affected', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['f_k_heat_device'] === null) {
            $invalidProperties[] = "'f_k_heat_device' can't be null";
        }
        if ($this->container['f_k_old_region'] === null) {
            $invalidProperties[] = "'f_k_old_region' can't be null";
        }
        if ($this->container['f_k_new_region'] === null) {
            $invalidProperties[] = "'f_k_new_region' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets f_k_heat_device
     *
     * @return int
     */
    public function getFKHeatDevice()
    {
        return $this->container['f_k_heat_device'];
    }

    /**
     * Sets f_k_heat_device
     *
     * @param int $f_k_heat_device f_k_heat_device
     *
     * @return self
     */
    public function setFKHeatDevice($f_k_heat_device)
    {
        if (is_null($f_k_heat_device)) {
            throw new \InvalidArgumentException('non-nullable f_k_heat_device cannot be null');
        }
        $this->container['f_k_heat_device'] = $f_k_heat_device;

        return $this;
    }

    /**
     * Gets heat_device
     *
     * @return \FWGCentralAPI\Model\HeatDevice|null
     */
    public function getHeatDevice()
    {
        return $this->container['heat_device'];
    }

    /**
     * Sets heat_device
     *
     * @param \FWGCentralAPI\Model\HeatDevice|null $heat_device heat_device
     *
     * @return self
     */
    public function setHeatDevice($heat_device)
    {
        if (is_null($heat_device)) {
            throw new \InvalidArgumentException('non-nullable heat_device cannot be null');
        }
        $this->container['heat_device'] = $heat_device;

        return $this;
    }

    /**
     * Gets f_k_old_region
     *
     * @return int
     */
    public function getFKOldRegion()
    {
        return $this->container['f_k_old_region'];
    }

    /**
     * Sets f_k_old_region
     *
     * @param int $f_k_old_region f_k_old_region
     *
     * @return self
     */
    public function setFKOldRegion($f_k_old_region)
    {
        if (is_null($f_k_old_region)) {
            throw new \InvalidArgumentException('non-nullable f_k_old_region cannot be null');
        }
        $this->container['f_k_old_region'] = $f_k_old_region;

        return $this;
    }

    /**
     * Gets old_region
     *
     * @return \FWGCentralAPI\Model\Region|null
     */
    public function getOldRegion()
    {
        return $this->container['old_region'];
    }

    /**
     * Sets old_region
     *
     * @param \FWGCentralAPI\Model\Region|null $old_region old_region
     *
     * @return self
     */
    public function setOldRegion($old_region)
    {
        if (is_null($old_region)) {
            throw new \InvalidArgumentException('non-nullable old_region cannot be null');
        }
        $this->container['old_region'] = $old_region;

        return $this;
    }

    /**
     * Gets f_k_new_region
     *
     * @return int
     */
    public function getFKNewRegion()
    {
        return $this->container['f_k_new_region'];
    }

    /**
     * Sets f_k_new_region
     *
     * @param int $f_k_new_region f_k_new_region
     *
     * @return self
     */
    public function setFKNewRegion($f_k_new_region)
    {
        if (is_null($f_k_new_region)) {
            throw new \InvalidArgumentException('non-nullable f_k_new_region cannot be null');
        }
        $this->container['f_k_new_region'] = $f_k_new_region;

        return $this;
    }

    /**
     * Gets new_region
     *
     * @return \FWGCentralAPI\Model\Region|null
     */
    public function getNewRegion()
    {
        return $this->container['new_region'];
    }

    /**
     * Sets new_region
     *
     * @param \FWGCentralAPI\Model\Region|null $new_region new_region
     *
     * @return self
     */
    public function setNewRegion($new_region)
    {
        if (is_null($new_region)) {
            throw new \InvalidArgumentException('non-nullable new_region cannot be null');
        }
        $this->container['new_region'] = $new_region;

        return $this;
    }

    /**
     * Gets old_database_name
     *
     * @return string|null
     */
    public function getOldDatabaseName()
    {
        return $this->container['old_database_name'];
    }

    /**
     * Sets old_database_name
     *
     * @param string|null $old_database_name old_database_name
     *
     * @return self
     */
    public function setOldDatabaseName($old_database_name)
    {
        if (is_null($old_database_name)) {
            array_push($this->openAPINullablesSetToNull, 'old_database_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('old_database_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['old_database_name'] = $old_database_name;

        return $this;
    }

    /**
     * Gets new_database_name
     *
     * @return string|null
     */
    public function getNewDatabaseName()
    {
        return $this->container['new_database_name'];
    }

    /**
     * Sets new_database_name
     *
     * @param string|null $new_database_name new_database_name
     *
     * @return self
     */
    public function setNewDatabaseName($new_database_name)
    {
        if (is_null($new_database_name)) {
            array_push($this->openAPINullablesSetToNull, 'new_database_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('new_database_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['new_database_name'] = $new_database_name;

        return $this;
    }

    /**
     * Gets migration_start
     *
     * @return \DateTime|null
     */
    public function getMigrationStart()
    {
        return $this->container['migration_start'];
    }

    /**
     * Sets migration_start
     *
     * @param \DateTime|null $migration_start migration_start
     *
     * @return self
     */
    public function setMigrationStart($migration_start)
    {
        if (is_null($migration_start)) {
            throw new \InvalidArgumentException('non-nullable migration_start cannot be null');
        }
        $this->container['migration_start'] = $migration_start;

        return $this;
    }

    /**
     * Gets migration_end
     *
     * @return \DateTime|null
     */
    public function getMigrationEnd()
    {
        return $this->container['migration_end'];
    }

    /**
     * Sets migration_end
     *
     * @param \DateTime|null $migration_end migration_end
     *
     * @return self
     */
    public function setMigrationEnd($migration_end)
    {
        if (is_null($migration_end)) {
            array_push($this->openAPINullablesSetToNull, 'migration_end');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('migration_end', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['migration_end'] = $migration_end;

        return $this;
    }

    /**
     * Gets rows_affected
     *
     * @return int|null
     */
    public function getRowsAffected()
    {
        return $this->container['rows_affected'];
    }

    /**
     * Sets rows_affected
     *
     * @param int|null $rows_affected rows_affected
     *
     * @return self
     */
    public function setRowsAffected($rows_affected)
    {
        if (is_null($rows_affected)) {
            array_push($this->openAPINullablesSetToNull, 'rows_affected');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rows_affected', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rows_affected'] = $rows_affected;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


